apiVersion: v1 #k8s api version
kind: Service #k8s resource kind we are creating
metadata: #meta data of the resource we are creating
  name: interceptor
spec:
  selector:
    app: interceptor
  ports:
    - protocol: "TCP"
      port: 8080 #the port the service is running on in the cluster
      targetPort: 8080 #the port exposed by the service
  type: NodePort #type of the service