server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mohan_schema
    username: root
    password: Ilp@123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
